// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: code.jflex

package com.cunoc.drymnz.plpgsql_studio.b_cases.analysis.sql;

import java_cup.runtime.Symbol;
import java.util.ArrayList;
import java.io.StringReader;

import com.cunoc.drymnz.plpgsql_studio.a_entidades.analyzer.ErrorTypeInTheInterpreter;
import com.cunoc.drymnz.plpgsql_studio.a_entidades.analyzer.ReportErrorInterpreter;
import com.cunoc.drymnz.plpgsql_studio.a_entidades.analyzer.Token;


@SuppressWarnings("fallthrough")
public class LexemaSQL implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int DATA_COLLECTION = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\25\u0100\1\u0200\11\u0100\1\u0300\17\u0100\1\u0400\247\u0100"+
    "\10\u0500\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\10\0\6\1\22\0\1\1\7\0\1\2\1\3\2\0"+
    "\1\4\1\5\1\6\1\0\12\7\1\0\1\10\1\11"+
    "\1\12\1\13\2\0\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\34\1\43\1\34\4\0\1\44\1\0"+
    "\1\45\1\34\1\46\1\34\1\47\3\34\1\50\2\34"+
    "\1\51\1\34\1\52\1\53\2\34\1\54\1\55\1\56"+
    "\4\34\1\57\1\34\1\60\1\1\1\61\7\0\1\1"+
    "\32\0\1\1\u01df\0\1\1\177\0\13\1\35\0\2\1"+
    "\5\0\1\1\57\0\1\1\240\0\1\1\u01ff\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\5\1\1\1\6"+
    "\1\7\25\10\1\1\2\11\2\0\22\10\1\12\1\13"+
    "\5\10\1\14\4\10\3\0\1\6\1\15\1\10\1\16"+
    "\13\10\1\17\1\10\1\20\2\10\1\21\6\10\1\22"+
    "\2\10\1\23\3\10\3\0\7\10\1\24\1\10\1\25"+
    "\3\10\1\26\1\27\1\30\1\10\1\31\7\10\1\32"+
    "\3\10\3\0\1\33\7\10\1\34\10\10\1\35\3\10"+
    "\1\36\1\37\1\40\1\0\1\10\1\41\1\10\1\42"+
    "\1\10\1\43\1\10\1\44\1\10\1\45\2\10\1\46"+
    "\1\47\1\50\1\51\1\52\1\10\1\0\1\53\1\10"+
    "\1\54\1\55\1\56\1\57\1\10\1\60\1\0\2\10"+
    "\1\0\2\10\1\0\1\61\1\62\22\0\1\63";

  private static int [] zzUnpackAction() {
    int [] result = new int[218];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\144\0\144\0\144\0\310"+
    "\0\372\0\144\0\u012c\0\u015e\0\u0190\0\u01c2\0\u01f4\0\u0226"+
    "\0\u0258\0\u028a\0\u02bc\0\u02ee\0\u0320\0\u0352\0\u0384\0\u03b6"+
    "\0\u03e8\0\u041a\0\u044c\0\u047e\0\u04b0\0\u04e2\0\u0514\0\u0546"+
    "\0\144\0\u0578\0\u05aa\0\u05dc\0\u060e\0\u0640\0\u0672\0\u06a4"+
    "\0\u06d6\0\u0708\0\u073a\0\u076c\0\u079e\0\u07d0\0\u0802\0\u0834"+
    "\0\u0866\0\u0898\0\u08ca\0\u08fc\0\u092e\0\u0960\0\u01f4\0\u01f4"+
    "\0\u0992\0\u09c4\0\u09f6\0\u0a28\0\u0a5a\0\u01f4\0\u0a8c\0\u0abe"+
    "\0\u0af0\0\u0b22\0\u0b54\0\u0b86\0\u0bb8\0\u05dc\0\u01f4\0\u0bea"+
    "\0\u01f4\0\u0c1c\0\u0c4e\0\u0c80\0\u0cb2\0\u0ce4\0\u0d16\0\u0d48"+
    "\0\u0d7a\0\u0dac\0\u0dde\0\u0e10\0\u0e42\0\u0e74\0\u01f4\0\u0ea6"+
    "\0\u0ed8\0\u01f4\0\u0f0a\0\u0f3c\0\u0f6e\0\u0fa0\0\u0fd2\0\u1004"+
    "\0\u01f4\0\u1036\0\u1068\0\u109a\0\u10cc\0\u10fe\0\u1130\0\u1162"+
    "\0\u1194\0\u11c6\0\u11f8\0\u122a\0\u125c\0\u128e\0\u12c0\0\u12f2"+
    "\0\u1324\0\u01f4\0\u1356\0\u01f4\0\u1388\0\u13ba\0\u13ec\0\u01f4"+
    "\0\u01f4\0\u01f4\0\u141e\0\u01f4\0\u1450\0\u1482\0\u14b4\0\u14e6"+
    "\0\u1518\0\u154a\0\u157c\0\u01f4\0\u15ae\0\u15e0\0\u1612\0\u1644"+
    "\0\u1676\0\u16a8\0\u01f4\0\u16da\0\u170c\0\u173e\0\u1770\0\u17a2"+
    "\0\u17d4\0\u1806\0\u01f4\0\u1838\0\u186a\0\u189c\0\u18ce\0\u1900"+
    "\0\u1932\0\u1964\0\u1996\0\u01f4\0\u19c8\0\u19fa\0\u1a2c\0\u01f4"+
    "\0\144\0\144\0\u1a5e\0\u1a90\0\u01f4\0\u1ac2\0\u01f4\0\u1af4"+
    "\0\u01f4\0\u1b26\0\u01f4\0\u1b58\0\u01f4\0\u1b8a\0\u1bbc\0\u01f4"+
    "\0\u01f4\0\u01f4\0\u01f4\0\u01f4\0\u1bee\0\u1c20\0\u01f4\0\u1c52"+
    "\0\u01f4\0\u01f4\0\u01f4\0\u01f4\0\u1c84\0\u01f4\0\u1cb6\0\u1ce8"+
    "\0\u1d1a\0\u1d4c\0\u1d7e\0\u1db0\0\u1de2\0\u01f4\0\u01f4\0\u1e14"+
    "\0\u1e46\0\u1e78\0\u1eaa\0\u1edc\0\u1f0e\0\u1f40\0\u1f72\0\u1fa4"+
    "\0\u1fd6\0\u2008\0\u203a\0\u206c\0\u209e\0\u20d0\0\u2102\0\u2134"+
    "\0\u2166\0\144";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[218];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\10\1\3\1\11"+
    "\1\12\3\3\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\17\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\17\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\15\17\1\40\1\3\11\41\1\42\50\41\63\0"+
    "\1\4\77\0\1\43\50\0\1\44\1\11\4\0\44\17"+
    "\11\0\1\17\4\0\3\17\1\45\7\17\1\46\1\17"+
    "\1\47\26\17\11\0\1\17\4\0\16\17\1\50\25\17"+
    "\11\0\1\17\4\0\16\17\1\51\2\17\1\52\22\17"+
    "\11\0\1\17\4\0\4\17\1\53\14\17\1\54\22\17"+
    "\11\0\1\17\4\0\44\17\11\0\1\17\4\0\16\17"+
    "\1\55\2\17\1\56\22\17\11\0\1\17\4\0\21\17"+
    "\1\57\22\17\11\0\1\17\4\0\15\17\1\60\26\17"+
    "\11\0\1\17\4\0\16\17\1\61\25\17\11\0\1\17"+
    "\4\0\4\17\1\62\37\17\11\0\1\17\4\0\4\17"+
    "\1\63\37\17\11\0\1\17\4\0\16\17\1\64\25\17"+
    "\11\0\1\17\4\0\16\17\1\65\5\17\1\66\17\17"+
    "\11\0\1\17\4\0\15\17\1\67\3\17\1\70\22\17"+
    "\11\0\1\17\4\0\21\17\1\71\22\17\11\0\1\17"+
    "\4\0\4\17\1\72\37\17\11\0\1\17\4\0\2\17"+
    "\1\73\1\17\1\74\37\17\11\0\1\17\4\0\1\75"+
    "\15\17\1\76\25\17\11\0\1\17\4\0\17\17\1\77"+
    "\2\17\1\100\21\17\11\0\1\17\4\0\1\101\43\17"+
    "\11\0\1\17\4\0\7\17\1\102\34\17\46\0\1\103"+
    "\27\0\1\104\116\0\1\105\21\0\1\106\61\0\1\17"+
    "\4\0\3\17\1\107\40\17\11\0\1\17\4\0\23\17"+
    "\1\110\20\17\11\0\1\17\4\0\3\17\1\111\40\17"+
    "\11\0\1\17\4\0\16\17\1\112\25\17\11\0\1\17"+
    "\4\0\13\17\1\113\1\17\1\114\26\17\11\0\1\17"+
    "\4\0\4\17\1\115\37\17\11\0\1\17\4\0\5\17"+
    "\1\116\5\17\1\117\30\17\11\0\1\17\4\0\16\17"+
    "\1\120\25\17\11\0\1\17\4\0\21\17\1\121\22\17"+
    "\11\0\1\17\4\0\16\17\1\122\25\17\11\0\1\17"+
    "\4\0\1\123\43\17\11\0\1\17\4\0\22\17\1\124"+
    "\1\125\20\17\11\0\1\17\4\0\10\17\1\126\33\17"+
    "\11\0\1\17\4\0\27\17\1\127\14\17\11\0\1\17"+
    "\4\0\5\17\1\130\36\17\11\0\1\17\4\0\3\17"+
    "\1\131\40\17\11\0\1\17\4\0\23\17\1\132\20\17"+
    "\11\0\1\17\4\0\13\17\1\133\30\17\11\0\1\17"+
    "\4\0\10\17\1\134\33\17\11\0\1\17\4\0\5\17"+
    "\1\135\17\17\1\136\16\17\11\0\1\17\4\0\7\17"+
    "\1\137\34\17\11\0\1\17\4\0\13\17\1\140\7\17"+
    "\1\141\20\17\11\0\1\17\4\0\1\17\1\142\42\17"+
    "\11\0\1\17\4\0\3\17\1\143\40\17\11\0\1\17"+
    "\4\0\4\17\1\144\37\17\11\0\1\17\4\0\13\17"+
    "\1\145\5\17\1\146\22\17\11\0\1\17\4\0\4\17"+
    "\1\147\37\17\7\0\1\150\61\0\1\151\122\0\1\152"+
    "\22\0\1\17\4\0\4\17\1\153\37\17\11\0\1\17"+
    "\4\0\13\17\1\154\30\17\11\0\1\17\4\0\24\17"+
    "\1\155\17\17\11\0\1\17\4\0\22\17\1\156\21\17"+
    "\11\0\1\17\4\0\1\157\43\17\11\0\1\17\4\0"+
    "\1\160\43\17\11\0\1\17\4\0\4\17\1\161\37\17"+
    "\11\0\1\17\4\0\17\17\1\162\24\17\11\0\1\17"+
    "\4\0\4\17\1\163\37\17\11\0\1\17\4\0\14\17"+
    "\1\164\27\17\11\0\1\17\4\0\15\17\1\165\26\17"+
    "\11\0\1\17\4\0\4\17\1\166\37\17\11\0\1\17"+
    "\4\0\4\17\1\167\11\17\1\170\25\17\11\0\1\17"+
    "\4\0\15\17\1\171\26\17\11\0\1\17\4\0\23\17"+
    "\1\172\20\17\11\0\1\17\4\0\10\17\1\173\33\17"+
    "\11\0\1\17\4\0\13\17\1\174\30\17\11\0\1\17"+
    "\4\0\14\17\1\175\27\17\11\0\1\17\4\0\4\17"+
    "\1\176\37\17\11\0\1\17\4\0\16\17\1\177\25\17"+
    "\11\0\1\17\4\0\4\17\1\200\37\17\11\0\1\17"+
    "\4\0\4\17\1\201\37\17\11\0\1\17\4\0\13\17"+
    "\1\202\30\17\11\0\1\17\4\0\1\203\43\17\11\0"+
    "\1\17\4\0\21\17\1\204\22\17\11\0\1\17\4\0"+
    "\24\17\1\205\17\17\11\0\1\17\4\0\2\17\1\206"+
    "\41\17\11\0\1\17\4\0\21\17\1\207\22\17\14\0"+
    "\1\210\113\0\1\211\66\0\1\212\17\0\1\17\4\0"+
    "\21\17\1\213\22\17\11\0\1\17\4\0\4\17\1\214"+
    "\37\17\11\0\1\17\4\0\14\17\1\215\27\17\11\0"+
    "\1\17\4\0\23\17\1\216\20\17\11\0\1\17\4\0"+
    "\23\17\1\217\20\17\11\0\1\17\4\0\24\17\1\220"+
    "\17\17\11\0\1\17\4\0\23\17\1\221\20\17\11\0"+
    "\1\17\4\0\10\17\1\222\33\17\11\0\1\17\4\0"+
    "\23\17\1\223\20\17\11\0\1\17\4\0\21\17\1\224"+
    "\22\17\11\0\1\17\4\0\6\17\1\225\35\17\11\0"+
    "\1\17\4\0\5\17\1\226\36\17\11\0\1\17\4\0"+
    "\1\227\43\17\11\0\1\17\4\0\21\17\1\230\22\17"+
    "\11\0\1\17\4\0\12\17\1\231\31\17\11\0\1\17"+
    "\4\0\14\17\1\232\27\17\11\0\1\17\4\0\2\17"+
    "\1\233\41\17\11\0\1\17\4\0\4\17\1\234\37\17"+
    "\11\0\1\17\4\0\23\17\1\235\20\17\11\0\1\17"+
    "\4\0\4\17\1\236\37\17\11\0\1\17\4\0\7\17"+
    "\1\237\34\17\11\0\1\17\4\0\4\17\1\240\37\17"+
    "\15\0\1\241\127\0\1\242\45\0\1\243\23\0\1\17"+
    "\4\0\1\244\43\17\11\0\1\17\4\0\15\17\1\245"+
    "\26\17\11\0\1\17\4\0\21\17\1\246\22\17\11\0"+
    "\1\17\4\0\4\17\1\247\37\17\11\0\1\17\4\0"+
    "\13\17\1\250\30\17\11\0\1\17\4\0\4\17\1\251"+
    "\37\17\11\0\1\17\4\0\6\17\1\252\35\17\11\0"+
    "\1\17\4\0\23\17\1\253\20\17\11\0\1\17\4\0"+
    "\4\17\1\254\37\17\11\0\1\17\4\0\27\17\1\255"+
    "\14\17\11\0\1\17\4\0\21\17\1\256\22\17\11\0"+
    "\1\17\4\0\4\17\1\257\37\17\11\0\1\17\4\0"+
    "\4\17\1\260\37\17\11\0\1\17\4\0\1\261\43\17"+
    "\11\0\1\17\4\0\23\17\1\262\20\17\11\0\1\17"+
    "\4\0\4\17\1\263\37\17\11\0\1\17\4\0\22\17"+
    "\1\264\21\17\11\0\1\17\4\0\1\265\43\17\56\0"+
    "\1\266\14\0\1\17\4\0\15\17\1\267\26\17\11\0"+
    "\1\17\4\0\1\270\43\17\11\0\1\17\4\0\23\17"+
    "\1\271\20\17\11\0\1\17\4\0\15\17\1\272\26\17"+
    "\11\0\1\17\4\0\21\17\1\273\22\17\11\0\1\17"+
    "\4\0\27\17\1\274\14\17\11\0\1\17\4\0\15\17"+
    "\1\275\26\17\11\0\1\17\4\0\21\17\1\276\22\17"+
    "\47\0\1\277\23\0\1\17\4\0\10\17\1\300\33\17"+
    "\11\0\1\17\4\0\2\17\1\301\41\17\50\0\1\302"+
    "\22\0\1\17\4\0\15\17\1\303\26\17\11\0\1\17"+
    "\4\0\4\17\1\304\37\17\52\0\1\305\20\0\1\17"+
    "\4\0\23\17\1\306\20\17\11\0\1\17\4\0\22\17"+
    "\1\307\21\17\55\0\1\310\60\0\1\311\56\0\1\312"+
    "\67\0\1\313\63\0\1\314\20\0\1\315\116\0\1\316"+
    "\60\0\1\317\65\0\1\320\57\0\1\321\60\0\1\322"+
    "\57\0\1\323\27\0\1\324\62\0\1\325\57\0\1\326"+
    "\72\0\1\327\46\0\1\330\102\0\1\331\44\0\1\332"+
    "\41\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[8600];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\3\11\2\1\1\11\26\1\1\11"+
    "\1\1\2\0\36\1\3\0\42\1\3\0\35\1\3\0"+
    "\26\1\2\11\1\0\22\1\1\0\10\1\1\0\2\1"+
    "\1\0\2\1\1\0\2\1\22\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[218];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    /*START-CODE*/

    private ArrayList<ReportErrorInterpreter> listError = new ArrayList();
    private String dataCollected = "";

    public LexemaSQL(String in) {
        this.zzReader = new StringReader(in);
    }
      
    private void print(String token) {
        System.out.println(token+ " < " + yytext() + " > <Linea\"" + (yyline + 1) + "\">" + "<Columna\"" + (yycolumn+1) + "\">");
    }

    private void addError(){
        print("error");
        ErrorTypeInTheInterpreter type = ErrorTypeInTheInterpreter.LEXICON;
        Token toke = new Token(yyline + 1, yycolumn + 1, yytext());
        this.listError.add(new ReportErrorInterpreter(type, toke, ""));
    }

    public ArrayList<ReportErrorInterpreter> getListError() {
        return this.listError;
    }
    
    public String getDataCollected(){
        return this.dataCollected;
    }

    public void setDataCollected(String newdataCollected){
        this.dataCollected = newdataCollected;
    }

    /*FINAL-CODE*/


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexemaSQL(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {   return new java_cup.runtime.Symbol(SymSQL.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { //MANEJAR EL ERROR LEXICO
                        print("ERROR");
                        addError();
            }
          // fall through
          case 52: break;
          case 2:
            { 
            }
          // fall through
          case 53: break;
          case 3:
            { print("(");         return new Symbol(SymSQL.OPEN_P       , yyline, yycolumn, yytext());
            }
          // fall through
          case 54: break;
          case 4:
            { print(")");         return new Symbol(SymSQL.CLOSE_P      , yyline, yycolumn, yytext());
            }
          // fall through
          case 55: break;
          case 5:
            { print(",");         return new Symbol(SymSQL.COMMA, yyline, yycolumn, yytext());
            }
          // fall through
          case 56: break;
          case 6:
            { print("IDENTIFICADOR"); return new Symbol(SymSQL.NUMEBERS     , yyline, yycolumn, yytext());
            }
          // fall through
          case 57: break;
          case 7:
            { print(";");         return new Symbol(SymSQL.PERIOD_AND_AS, yyline, yycolumn, yytext());
            }
          // fall through
          case 58: break;
          case 8:
            { print("IDENTIFICADOR"); return new Symbol(SymSQL.IDENTIFICADOR, yyline, yycolumn, yytext());
            }
          // fall through
          case 59: break;
          case 9:
            { dataCollected += yytext();
            }
          // fall through
          case 60: break;
          case 10:
            { print("ON");         return new Symbol(SymSQL.ON        , yyline, yycolumn, yytext());
            }
          // fall through
          case 61: break;
          case 11:
            { print("OR");         return new Symbol(SymSQL.OR        , yyline, yycolumn, yytext());
            }
          // fall through
          case 62: break;
          case 12:
            { print("TO");         return new Symbol(SymSQL.TO        , yyline, yycolumn, yytext());
            }
          // fall through
          case 63: break;
          case 13:
            { print("ADD");        return new Symbol(SymSQL.ADD       , yyline, yycolumn, yytext());
            }
          // fall through
          case 64: break;
          case 14:
            { print("AND");        return new Symbol(SymSQL.AND       , yyline, yycolumn, yytext());
            }
          // fall through
          case 65: break;
          case 15:
            { print("INT");        return new Symbol(SymSQL.INT       , yyline, yycolumn, yytext());
            }
          // fall through
          case 66: break;
          case 16:
            { print("KEY");        return new Symbol(SymSQL.KEY       , yyline, yycolumn, yytext());
            }
          // fall through
          case 67: break;
          case 17:
            { print("NOT");        return new Symbol(SymSQL.NOT       , yyline, yycolumn, yytext());
            }
          // fall through
          case 68: break;
          case 18:
            { print("SET");        return new Symbol(SymSQL.SET       , yyline, yycolumn, yytext());
            }
          // fall through
          case 69: break;
          case 19:
            { print("USE");        return new Symbol(SymSQL.USE       , yyline, yycolumn, yytext());
            }
          // fall through
          case 70: break;
          case 20:
            { print("DROP");       return new Symbol(SymSQL.DROP      , yyline, yycolumn, yytext());
            }
          // fall through
          case 71: break;
          case 21:
            { print("FROM");       return new Symbol(SymSQL.FROM      , yyline, yycolumn, yytext());
            }
          // fall through
          case 72: break;
          case 22:
            { print("INTO");       return new Symbol(SymSQL.INTO      , yyline, yycolumn, yytext());
            }
          // fall through
          case 73: break;
          case 23:
            { print("JOIN");       return new Symbol(SymSQL.JOIN      , yyline, yycolumn, yytext());
            }
          // fall through
          case 74: break;
          case 24:
            { print("LEFT");       return new Symbol(SymSQL.LEFT      , yyline, yycolumn, yytext());
            }
          // fall through
          case 75: break;
          case 25:
            { print("NULL");       return new Symbol(SymSQL.NULL      , yyline, yycolumn, yytext());
            }
          // fall through
          case 76: break;
          case 26:
            { print("USER");       return new Symbol(SymSQL.USER      , yyline, yycolumn, yytext());
            }
          // fall through
          case 77: break;
          case 27:
            { print("ALTER");      return new Symbol(SymSQL.ALTER     , yyline, yycolumn, yytext());
            }
          // fall through
          case 78: break;
          case 28:
            { print("GRANT");      return new Symbol(SymSQL.GRANT     , yyline, yycolumn, yytext());
            }
          // fall through
          case 79: break;
          case 29:
            { print("TABLE");      return new Symbol(SymSQL.TABLE     , yyline, yycolumn, yytext());
            }
          // fall through
          case 80: break;
          case 30:
            { print("WHERE");      return new Symbol(SymSQL.WHERE     , yyline, yycolumn, yytext());
            }
          // fall through
          case 81: break;
          case 31:
            { yybegin(DATA_COLLECTION);
                    print("{_-=>"); 
                    return new Symbol(SymSQL.START_HARVESTING ,yyline,yycolumn,yytext());
            }
          // fall through
          case 82: break;
          case 32:
            { yybegin(YYINITIAL);
                    print("<=-_}"); 
                    return new Symbol(SymSQL.OUT_HARVESTING ,yyline,yycolumn,yytext());
            }
          // fall through
          case 83: break;
          case 33:
            { print("COLUMN");     return new Symbol(SymSQL.COLUMN    , yyline, yycolumn, yytext());
            }
          // fall through
          case 84: break;
          case 34:
            { print("CREATE");     return new Symbol(SymSQL.CREATE    , yyline, yycolumn, yytext());
            }
          // fall through
          case 85: break;
          case 35:
            { print("DELETE");     return new Symbol(SymSQL.DELETE    , yyline, yycolumn, yytext());
            }
          // fall through
          case 86: break;
          case 36:
            { print("INSERT");     return new Symbol(SymSQL.INSERT    , yyline, yycolumn, yytext());
            }
          // fall through
          case 87: break;
          case 37:
            { print("MODIFY");      return new Symbol(SymSQL.MODIFY    , yyline, yycolumn, yytext());
            }
          // fall through
          case 88: break;
          case 38:
            { print("REVOKE");     return new Symbol(SymSQL.REVOKE    , yyline, yycolumn, yytext());
            }
          // fall through
          case 89: break;
          case 39:
            { print("SCHEMA");     return new Symbol(SymSQL.SCHEMA    , yyline, yycolumn, yytext());
            }
          // fall through
          case 90: break;
          case 40:
            { print("SELECT");     return new Symbol(SymSQL.SELECT    , yyline, yycolumn, yytext());
            }
          // fall through
          case 91: break;
          case 41:
            { print("UPDATE");     return new Symbol(SymSQL.UPDATE    , yyline, yycolumn, yytext());
            }
          // fall through
          case 92: break;
          case 42:
            { print("VALUES");     return new Symbol(SymSQL.VALUES    , yyline, yycolumn, yytext());
            }
          // fall through
          case 93: break;
          case 43:
            { print("BOOLEAN");    return new Symbol(SymSQL.BOOLEAN   , yyline, yycolumn, yytext());
            }
          // fall through
          case 94: break;
          case 44:
            { print("DEFAULT");    return new Symbol(SymSQL.DEFAULT   , yyline, yycolumn, yytext());
            }
          // fall through
          case 95: break;
          case 45:
            { print("FOREIGN");    return new Symbol(SymSQL.FOREIGN   , yyline, yycolumn, yytext());
            }
          // fall through
          case 96: break;
          case 46:
            { print("INTEGER");    return new Symbol(SymSQL.INTEGER   , yyline, yycolumn, yytext());
            }
          // fall through
          case 97: break;
          case 47:
            { print("PRIMARY");    return new Symbol(SymSQL.PRIMARY   , yyline, yycolumn, yytext());
            }
          // fall through
          case 98: break;
          case 48:
            { print("VARCHAR");    return new Symbol(SymSQL.VARCHAR   , yyline, yycolumn, yytext());
            }
          // fall through
          case 99: break;
          case 49:
            { print("CONSTRAINT"); return new Symbol(SymSQL.CONSTRAINT, yyline, yycolumn, yytext());
            }
          // fall through
          case 100: break;
          case 50:
            { print("REFERENCES"); return new Symbol(SymSQL.REFERENCES, yyline, yycolumn, yytext());
            }
          // fall through
          case 101: break;
          case 51:
            { print("DECLARE");    return new Symbol(SymSQL.DECLARE   , yyline, yycolumn, yytext());
            }
          // fall through
          case 102: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
