
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.cunoc.drymnz.plpgsql_studio.b_cases.analysis.sql;

/** CUP generated interface containing symbol constants. */
public interface SymSQL {
  /* terminals */
  public static final int HTML = 6;
  public static final int EQUAL = 4;
  public static final int OUT_HARVESTING = 8;
  public static final int EOF = 0;
  public static final int SCRIPTING = 7;
  public static final int ID = 5;
  public static final int CapTcha = 2;
  public static final int error = 1;
  public static final int START_HARVESTING = 9;
  public static final int FinCapTcha = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CapTcha",
  "FinCapTcha",
  "EQUAL",
  "ID",
  "HTML",
  "SCRIPTING",
  "OUT_HARVESTING",
  "START_HARVESTING"
  };
}

