
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.cunoc.drymnz.plpgsql_studio.b_cases.analysis.ejemplo;

/** CUP generated class containing symbol constants. */
public class SymEjemplo {
  /* terminals */
  public static final int error = 1;
  public static final int OUT_HARVESTING = 3;
  public static final int CapTcha = 2;
  public static final int EOF = 0;
  public static final int START_HARVESTING = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CapTcha",
  "OUT_HARVESTING",
  "START_HARVESTING"
  };
}

